services:
  - type: web
    name: e-procurement-portal
    env: node
    region: oregon
    buildCommand: npm install --prefix Server && npm install --prefix Client && npm run build --prefix Client
    startCommand: npm start --prefix Server
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false

